version: '3.8'

services:
  order-api:
    build:
      context: ./src/
      dockerfile: OrderApiDockerfile
    restart: on-failure
    ports:
      - "8080:80"
    depends_on:
      - rabbitmq
      - elasticsearch

  after-order:
    build:
      context: ./src/
      dockerfile: AfterOrderDockerfile
    restart: on-failure
    depends_on:
      - redis
      - rabbitmq
      - elasticsearch

  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
      - xpack.security.enabled=false

volumes:
  elasticsearch-data:
    driver: local